spring:
  datasource:
    url: jdbc:mysql://rm-2zee878d65v2tw3idao.mysql.rds.aliyuncs.com/user_center?nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: 19881122yl^
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # nacos server 的地址
        server-addr: localhost:8848
  application:
    name: user-center