spring:
  datasource:
    url: jdbc:mysql://rm-2zee878d65v2tw3idao.mysql.rds.aliyuncs.com/content_center?nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: 19881122yl^
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # nacos server 的地址
        server-addr: 112.126.97.128:8848
#        namespace: 65a56cb9-82d4-44a9-a08b-dd80d1e749f3
        cluster-name: BJ
        metadata:
          # 自己实例的版本
          version: v1
          # 允许调用的提供者版本
          target-version: v1
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true

server:
  port: 8010

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    com.jerry.contentcenter.feignclient.UserCenterFeignClient: debug

feign:
  client:
    config:
#      # 想要调用的微服务名称
#      user-center:
#        loggerLevel: full
      # 全局配置
      default:
        loggerLevel: full
