spring:
  datasource:
    url: jdbc:mysql://rm-2zee878d65v2tw3idao.mysql.rds.aliyuncs.com/content_center?nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: 19881122yl^
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8010